apiVersion: v1
values:
  images:
    ldap: "registry.cloudogu.com/k8s/ldap:2.6.8-7"
patches:
  values.yaml:
    image:
      registry: "{{ registryFrom .images.ldap }}"
      repository: "{{ repositoryFrom .images.ldap }}"
      tag: "{{ tagFrom .images.ldap }}"
