apiVersion: v1
values:
  images:
    ldap: "registry.cloudogu.com/official/ldap:2.6.10-6"
    kubectl: "docker.io/alpine/kubectl:1.35.3"
patches:
  values.yaml:
    image:
      registry: "{{ registryFrom .images.ldap }}"
      repository: "{{ repositoryFrom .images.ldap }}"
      tag: "{{ tagFrom .images.ldap }}"
    migration:
      hook:
        image:
          repository: '{{ printf "%s/%s" (registryFrom .images.kubectl) (repositoryFrom .images.kubectl) }}'
          tag: "{{ tagFrom .images.kubectl }}"
    persistence:
      resize:
        hook:
          image:
            repository: '{{ printf "%s/%s" (registryFrom .images.kubectl) (repositoryFrom .images.kubectl) }}'
            tag: "{{ tagFrom .images.kubectl }}"
