apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ldap.fullname" . }}-config
  labels:
    {{- include "ldap.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ toYaml .Values.config | indent 4 }}
  sensitive-config.yaml: |-
    {}
