apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap.fullname" . }}-sensitive-config
  labels:
    {{- include "ldap.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |-
{{ include "ldap.expandSlashKeys" (list .Values.sensitiveConfig) | indent 4 }}
