{{- $casCfg := .Values.secrets.serviceAccounts.cas -}}
{{- $usermgtCfg := .Values.secrets.serviceAccounts.usermgt -}}
{{- $ldapMapperCfg := .Values.secrets.serviceAccounts.ldapMapper -}}

{{- $renderCas := and $casCfg.enabled $casCfg.secret.create -}}
{{- $renderUsermgt := and $usermgtCfg.enabled $usermgtCfg.secret.create -}}
{{- $renderLdapMapper := and $ldapMapperCfg.enabled $ldapMapperCfg.secret.create -}}

{{- if $renderCas }}
{{ include "ldap.renderServiceAccountSecret" (dict "root" . "accountKey" "cas" "accountConfig" $casCfg "defaultUsername" "cas" "accessType" "rw") }}
{{- end }}

---
{{- if $renderUsermgt }}
{{ include "ldap.renderServiceAccountSecret" (dict "root" . "accountKey" "usermgt" "accountConfig" $usermgtCfg "defaultUsername" "usermgt" "accessType" "rw") }}
{{- end }}

---
{{- if $renderLdapMapper }}
{{ include "ldap.renderServiceAccountSecret" (dict "root" . "accountKey" "ldapMapper" "accountConfig" $ldapMapperCfg "defaultUsername" "ldap-mapper" "accessType" "ro") }}
{{- end }}
